#coding=utf-8
import os
import unittest
from webstruct.htmls import get_lines

CASES = [
    ('1.html', '', {
        'lines': [
            u'Contact Us  | UCD Earth Institute',
            u'UCD Home | About UCD | UCD News & Events | Virtual Tour | Contact UCD | Staff Directories | UCD Sitemap | UCD Connect',
            u'Home',
            u'About Us',
            u'News & Events',
            u'Research',
            u'People',
            u'Education',
            u'You are here:  Earth Institute   /   About us   /  Contact Us',
            u'About us',
            u'Mission & vision',
            u'Research Outputs',
            u'UCD Science Centre',
            u'Opportunities',
            u'Contact Us',
            u'Contact Us',
            u'UCD Earth Institute,',
            u'UCD Science Centre South,',
            u'University College Dublin,',
            u'Belfield, Dublin 4, Ireland',
            u'E:   earth.institute@ucd.ie',
            u'T: +353 1 716 2600',
            u'Click here if you wish to join our mailing list for notifications of all upcoming seminars and events',
            u'Privacy | Freedom of Information | Disclaimer | Sitemap |',
            u'© Copyright, University College Dublin 2011'],
        }),

    ('8.html', '', {
        'lines': [
            u'Athletics Ireland  AAI   » Contact Information',
            u'Competition',
            u'Statistics',
            u'Results',
            u'On-Line Entry Guide',
            u'Entry Forms',
            u'Permits',
            u'Rules and Regulations',
            u'Officials',
            u'Technical Committee',
            u'Ultra Running',
            u'Fixtures',
            u'National Championships',
            u'Licensed Events',
            u'Road Races',
            u'Coaching',
            u'Regional Development Team',
            u'National Event Squads',
            u'Coach Education',
            u'Coaching Resources',
            u'Coaching Conferences',
            u'Development / Clubs',
            u'Development',
            u'Coaching Education',
            u'Regional Development Team',
            u'Little Athletics',
            u'Fun Running Fit4life',
            u'Club Mark',
            u'Clubs',
            u'How to Start a Club',
            u'Benefits of Club Membership',
            u'Find a Club',
            u'Links',
            u'Child Welfare',
            u'Juvenile',
            u'Results',
            u'Juvenile All-Stars',
            u'Child Welfare',
            u'Facebook',
            u'Juvenile Competition Booklet',
            u'Schools',
            u'Results',
            u'Fixtures',
            u'Aviva Irish Schools Mile Challenge',
            u'Child Welfare',
            u'Facebook',
            u'High Performance',
            u'Registration',
            u'Registration System Login',
            u'FAQ',
            u'User Manual',
            u'Benefits of Membership',
            u'Insurance Information',
            u'Transfer Form',
            u'About Us',
            u'Contact Us',
            u'Our Board Members',
            u'Staff',
            u'History',
            u'Vision & Strategy',
            u'Governance',
            u'European Team Champs',
            u'Live Results',
            u'National Events',
            u'Licensed Fixture List',
            u'Subscribe Now',
            u'Coach Education Courses',
            u'EShop',
            u'Contact Information',
            u'Telephone',
            u'+ 353 (0)1 8869933',
            u'Fax',
            u'+ 353 (0)1 8421334',
            u'Address',
            u'Athletic Association of Ireland',
            u'Unit 19, Northwood Court',
            u'Northwood Business Campus',
            u'Santry,',
            u'Dublin 9',
            u'Ireland',
            u'Email  Office',
            u'admin@athleticsireland.ie',
            u'Email  CEO',
            u'ceo@athleticsireland.ie',
            u'Email High Performance Manager',
            u'performance@athleticsireland.ie',
            u'Email Athlete Services Coordinator',
            u'athleteservices@athleticsireland.ie',
            u'Email High Performance Teams Coordinator',
            u'teams@athleticsireland.ie',
            u'Email  Director of Coaching',
            u'coaching@athleticsireland.ie',
            u'Email Director of Development',
            u'development@athleticsireland.ie',
            u'Email Marketing Manager',
            u'marketing@athleticsireland.ie',
            u'Email Competition',
            u'competition@athleticsireland.ie',
            u'Email Registration',
            u'registrations@athleticsireland.ie',
            u'Email Schools Athletics',
            u'schools@athleticsireland.ie',
            u'Email Webmaster',
            u'marketing@athleticsireland.ie',
            u'Email Statistics Updates',
            u'statistics@athleticsireland.ie',
            u'Email Irish Runner Editor',
            u'editor@irishrunner.ie',
            u'Email Finance Director',
            u'finance@athleticsireland.ie',
            u'Email President Ciarán O Catháin',
            u'cocathain@AIT.IE',
            u'View Google Map',
            u'Directions from various routes are:',
            u'Approaching from the M50 Northbound:',
            u'Leave M50 at junction 4 (signposted Ballymun, City Centre), then at  roundabout take the 3rd exit onto the R108.  Take left hand just before the service station into Northwood Business Campus.  Take first left hand turn onto Northwood Crescent and  proceed onto Northwood Court.',
            u'Approaching from the M50 Southbound:',
            u'Leave M50 at junction 4 (signposted Ballymun, City Centre) and then at roundabout take the first exit onto the R108. Proceed as above.',
            u'Approaching from Santry Stadium:',
            u'Proceed towards the Airport on the Swords Road.  Take Left hand turn at the Crown Plaza Hotel into Northwood Business Campus.  Take last left hand turn onto Northwood Crescent and proceed onto Northwood Court.',
            u'Road Races and Events',
            u'Please contact marketing@ athleticsireland.ie to advertise here',
            u'Affiliated Bodies',
            u'Sponsors',
            u'© 1996-2009 - Athletic Association of Ireland | Web Design by irenses | Website Privacy Policy',
            u'© 1996-2012 - Athletic Association of Ireland'
        ]
    }),

    ('10.html', '', {
        'lines': [
            u'The Private Security Authority',
            u'http://www.psa.gov.ie/Website/psa/psa.nsf  https://www.psa.gov.ie/Website/psa/psa.nsf  http://www.psa.gov.ie/Website\PSA\SLiCMA_public.nsf  https://www.psa.gov.ie/Website\PSA\SLiCMA_public.nsf  http://www.psa.gov.ie/Website\PSA\empSLiCMA_public.nsf  https://www.psa.gov.ie/Website\PSA\empSLiCMA_public.nsf  http://www.psa.gov.ie/Website/psa/Enforcement_Public.nsf  https://www.psa.gov.ie/Website/psa/Enforcement_Public.nsf',
            u'Home',
            u'About the PSA',
            u'Forms',
            u'Licence Holders Register',
            u'News',
            u'Contact Us',
            u'Training & Standards',
            u'Legislation',
            u'Press Releases',
            u'FAQs',
            u'Licensing Information',
            u'PSA Publications',
            u'Report Unlicensed Security Services',
            u'Search News',
            u'Search Text',
            u'The Private Security Services Act 2004  Commencement Orders',
            u'PSA Publications',
            u'Mission Statement  Profile of our CEO  Membership of the PSA  Functions of the PSA',
            u'Contractors  Employees',
            u'Contracting Companies  Employees',
            u'Training  Standards  Training Providers',
            u'Contacting the PSA',
            u'Address:',
            u'The Private Security Authority,',
            u'Davis Street,',
            u'Tipperary Town',
            u'Telephone:',
            u'(062) 31588/32600',
            u'(062) 32628/32624          32614/32612 for Contractor Licensing',
            u'Fax:',
            u'(062) 31591 (Licensing Division)',
            u'Email:',
            u"info@psa.gov.ie      (the Authority's Licensing Division can be contacted at licensing@psa.gov.ie)",
            u"Web Site:",
            u'www.psa.gov.ie',
            u'The Private Security Authority, Davis Street, Tipperary Town.',
            u'Telephone: (062) 31588/32600      or     (062) 32628/32624          32614/32612 for Contractor Licensing',
            u'Fax: (062) 31591 (Licensing Division)     or     (062) 31731 (Other Enquiries)',
            u"Email: info@psa.gov.ie      (the Authority's Licensing Division can be contacted at licensing@psa.gov.ie)",
            ]
    }),

    ('26.html', '', {
        'lines': [
            u'Contact Us - This is Cavan!',
            u'skip to content',
            u'Search for:',
            u'Why Cavan?',
            u'Quality Product',
            u'Differentiation',
            u'Identity',
            u'Investing in Cavan',
            u'Foreign Direct Investment',
            u'Indigenous Development',
            u'Key Sectors',
            u'How we can help',
            u'News & Events',
            u'News',
            u'Events',
            u'Join Mailing List',
            u'RSS',
            u'Home',
            u'Business',
            u'Help',
            u'Contact Us',
            u'Help',
            u'Contact Us',
            u'Cookie & Privacy policy',
            u'Terms of Use',
            u'Site Map',
            u'Contact Us',
            u'You can get additional information and contact details for Cavan through the links provided below.',
            u'Economic Development Unit',
            u'Cavan County Council',
            u'+353 49 4378606',
            u'edu@cavancoco.ie',
            u'Cavan County Enterprise Board',
            u'Cavan Innovation and Technology Centre,',
            u'Dublin Road,',
            u'Cavan.',
            u'+ 353 49 4377200',
            u'info@cceb.ie',
            u'Find us on',
            u'Twitter',
            u'Facebook',
            u'YouTube',
            u'Help',
            u'Contact Us',
            u'Cookie & Privacy policy',
            u'Terms of Use',
            u'Site Map',
            u'Our other sites',
            u'Cavan Tourism',
            u'Cavan Arts',
            u'Cavan Sports',
            u'Cavan County Council',
            u'Get email updates',
            u'Sign up for email updates and special offers from Cavan!',
            u'This is Cavan is the official guide to doing business in Cavan, Ireland.',
            u'© 2013 Cavan Enterprise Board. Johnston Central Library, Farnham Street, Cavan. All rights reserved.',
            u'Pixel Design'
        ]
    }),

    ('41.html', '', {
        'lines': [
            u'Yellowstone  Contact Us » Yellowstone',
            u'Home',
            u'About Us',
            u'People',
            u'Portfolio',
            u'Practice Areas',
            u'Print',
            u'Exhibitions',
            u'Web',
            u'Multimedia',
            u'Fulfillment',
            u'Case Studies',
            u'Dublin City Development Plan',
            u'Dorian Gray',
            u'Words On The Street',
            u'Contact Us',
            u'Contact Us',
            u'Name *',
            u'* Please enter your name',
            u'Email *',
            u'* Please enter a valid email address',
            u'Message *',
            u'* Please enter message',
            u'Information',
            u'You can use these information to contact us or Just using the form below.',
            u'Our new address and contact details from the 7th August!',
            u'Contact Us',
            u'Yellowstone',
            u'Newmarket Hall',
            u'Newmarket Square',
            u'Dublin 8',
            u'T. 01 453 7554',
            u'F. 01 453 7871',
            u'W. www.yellowstone.ie',
            u'E. info@yellowstone.ie',
            u'Social network',
            u'Recent Work',
            u'Contact Details',
            u'Yellowstone',
            u'Newmarket Hall',
            u'Newmarket Square',
            u'Dublin 8',
            u'info@yellowstone.ie',
            u'T. 01 453 7554',
            u'F. 01 453 7871',
            u"size=\u201dbadge\u201d>", # should remove it
            u'Contact Form',
            u'Name',
            u'Email',
            u'Message',
            u'If you want to submit this form, do not enter anything in this field',
            u'Copyright © 2012 YCD Ltd. All rights reserved.'
        ]
    }),

    ('47.html', '', {
        'lines': [
            u'Contact Information',
            u'Q U A',
            u'E S T U S',
            u'Strategy & Marketing Consultants',
            u'Contact us for more information',
            u'Quaestus Ltd',
            u'38 Castle Park',
            u'Monkstown',
            u'Co Dublin',
            u'Ireland',
            u'Ph: +353 87 2565714',
            u'email@quaestus.ie'
        ]
    }),

    ('168.html', '', {
        'lines': [
            u'Ruairi Quinn TD » Contact Me',
            u'Ruairi Quinn TD',
            u'About',
            u'Contact Me',
            u'Advice Centres',
            u'Contact Me',
            u'You can contact me at:',
            u'Ruairi Quinn TD',
            u'Leinster House',
            u'Kildare Street',
            u'Dublin 2',
            u'Ireland',
            u'Or on +353 1 618 3434.',
            u'My email is: minister@education.gov.ie',
            u'Alternatively, just fill in the contact form below:',
            u'Your Name   (required)',
            u'Email   (valid email required)',
            u'Website',
            u'Message',
            u'cforms contact form by delicious:days',
            u'Pages',
            u'About',
            u'Contact Me',
            u'Advice Centres',
            u'Our team in Dublin South-East',
            u'Cllr Dermot Lacey',
            u'Cllr Gerry Ashe',
            u'Cllr Maria Parodi',
            u'Cllr Mary Freehill',
            u'Cllr Oisin Quinn',
            u'Kevin Humphreys TD',
            u'Welcome to the website of Ruairi Quinn, TD, Minister for Education and Skills.',
            u'Theme by ThemeZee.com'
        ]
    }),

    ('br.html', 'http://www.ecobaby.ie/catalog/', {
        'lines': [
            u'Ecobaby Ltd',
            u'Cart Contents    Checkout    My Account',
            u'Home » Catalogue',
            u'Welcome to Ecobaby Ltd',
            u'Welcome Guest! Would you like to  log yourself in  ? Or would you prefer to  create an account  ?',
            u'Welcome to the Ecobaby catalogue pages. We hope you find what you are looking for. If you would like any further information about our products, please contact us at:',
            u'Ecobaby Ltd',
            u'61 Park West Enterprise Centre',
            u'Lavery Avenue',
            u'Dublin 12',
            u'Ireland',
            u'Telephone CallSave 1850 52-52-53 (Republic of Ireland)',
            u'Telephone +353-1-620 5050 (Northern Ireland and International)',
            u'Fax +353-1-620 7966',
            u'email info [at] ecobaby.ie',
            u'About ordering online.',
            u'If you have any questions regarding your order please call us (for the price of a local call) on 1850 52-52-53 or on 01-6205050. We very much hope that you enjoy your shopping experience with Ecobaby.',
            u'New Products For July',
            u'Fashy Swim Nappy Pants pink frills 2yrs+',
            u'7.99EUR',
            u'Moltex Eco "Nature No.1" Size 2 / Mini 3-6kg 44 in pack',
            u'12.99EUR',
            u'Bio-D Concentrated Eucalyptus Disinfectant 1L',
            u'3.49EUR',
            u'Faith in Nature Dishwasher Gel 500ml',
            u'5.99EUR',
            u'Weleda Arnica Massage Balm - 100ml',
            u'13.50EUR',
            u'Weleda Arnica Ointment - Sprains & Bruises - 50ml',
            u'9.29EUR',
            u'Water Filter Element, Simply, Super Carb',
            u'48.89EUR',
            u'Faith Hemp Meadow Foam Conditioner 400ml',
            u'7.75EUR',
            u'Natracare Ultrapad Wings Long 10',
            u'3.04EUR',
            u'Categories',
            u'Ecobaby Gift Voucher  (1)',
            u'Eco Friendly Baby Nappies  (9)',
            u'Baby Food->  (4)',
            u"Lilly's Eco Clean - IRISH MADE  (17)",
            u'Premature Size Nappies',
            u'Cleaning the Home  (34)',
            u'Dishwashing  (15)',
            u'Laundry  (19)',
            u'Baby Clothing  (13)',
            u'Baby Care Products  (12)',
            u'Personal Care Products  (33)',
            u'Sanitary Products  (13)',
            u'Supplements, Vitamins, Tonics  (3)',
            u'Woolens  (4)',
            u"What's New?",
            u'Weleda Arnica Ointment - Sprains & Bruises - 50ml',
            u'9.29EUR',
            u'Quick Find',
            u'Use keywords to find the product you are looking for.',
            u'Advanced Search',
            u'Information',
            u'Shipping & Returns',
            u'Privacy Notice',
            u'Conditions of Use',
            u'Contact Us',
            u'Follow Us',
            u'Shopping Cart',
            u'0 items',
            u'Bestsellers',
            u'Baby Wipes - Moltex Unscented - 72/Pack',
            u'(Size 3) Moltex Eco Nappies - Midi - 80/Pack',
            u'Moltex Eco "Nature No.1" Size 5 / Junior 11-25kg 32 pack',
            u'Specials',
            u'Ecover Floor Soap - 1l',
            u'4.25EUR',
            u'4.29EUR',
            u'Find Out About...',
            u'Ecobaby Ltd',
            u'Eco Nappies',
            u'Nappy Disposal',
            u'Our Awards  Our Environmental Policies',
            u'Latest Awards',
            u'2008-2010 Parents Choice of Environmentally Friendly Product Range',
            u'Monday 22 July, 2013',
            u'Ecobaby Limited, 61 Park West Enterprise Ctr., Lavery Ave., Dublin 12. Callsave 1850 52-52-53',
            u'Copyright © 2006-2013 Ecobaby Ltd',
            u'Powered by osCommerce',
            u'Site design by Jean O’Brien',
        ]
    })
]


class ParserTestCase(unittest.TestCase):
    def _get_html(self, fn):
        path = os.path.join(os.path.dirname(__file__), 'htmlpages', fn)
        return open(path, 'rb').read().decode('utf-8')

    def test_pages(self):
        for fn, url, case in CASES:
            body = self._get_html(fn)
            for k, v in case.iteritems():
                if k == 'lines':
                    r = get_lines(body)
                self.assertEqual(r, v)

if __name__ == '__main__':
    unittest.main()